# the new trusty images of Travis cause build errors with psycopg2, see https://github.com/travis-ci/travis-ci/issues/8897
dist: trusty
group: deprecated-2017Q4

language: python
sudo: required

jobs:
  include:
    - python: "2.7"
      env: CKANVERSION=master
    - python: "3.6"
      env: CKANVERSION=master
    - python: "2.7"
      env: CKANVERSION=2.8
    - python: "2.7"
      env: CKANVERSION=2.7
    - python: "2.7"
      env: CKANVERSION=2.6
    - python: "2.7"
      env: CKANVERSION=2.5
    - python: "2.7"
      env: CKANVERSION=2.4

install:
    - bash bin/travis-build.bash
services:
    - redis-server
    - postgresql
script: bash bin/travis-run.bash
before_install:
    - pip install codecov
after_success:
    - codecov
